language: php
sudo: false

services:
  - memcached
  - redis-server

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

before_script:
  - composer update -o --no-interaction --ignore-platform-reqs
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - vendor/bin/phpunit --coverage-clover build/coverage/clover.xml

after_success:
  - vendor/bin/codacycoverage clover build/coverage/clover.xml

notifications:
  email: false