language: php
os: linux
dist: xenial

notifications:
  email: false

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

services:
  - memcached
  - redis

addons:
  hosts:
    - redis
    - memcached

before_install:
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - redis-cli ping

install:
  - composer update -o --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
