language: php

sudo: false

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - redis-server

addons:
  hosts:
    - redis
    - memcached

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true

before_install:
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer update -o --no-interaction --ignore-platform-reqs

before_script:
  - redis-cli ping

script:
  - vendor/bin/phpunit --coverage-clover build/coverage/clover.xml

after_success:
  - travis_retry vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage/clover.xml
